name: 'MU Semantic Diff'
description: 'Run MU semantic diff on pull requests and post results as PR comments'
author: 'MU Team'

branding:
  icon: 'git-pull-request'
  color: 'purple'

inputs:
  base:
    description: 'Base ref to compare against (default: PR base SHA)'
    required: false
    default: ''
  head:
    description: 'Head ref to compare (default: PR head SHA)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for posting comments (default: github.token)'
    required: false
    default: ${{ github.token }}
  comment:
    description: 'Post diff as PR comment (default: true)'
    required: false
    default: 'true'
  artifact:
    description: 'Upload full diff as artifact (default: false)'
    required: false
    default: 'false'
  artifact-name:
    description: 'Name of the artifact (default: mu-diff)'
    required: false
    default: 'mu-diff'
  max-comment-size:
    description: 'Maximum comment size in characters before truncating (default: 60000)'
    required: false
    default: '60000'
  working-directory:
    description: 'Working directory for running mu diff (default: .)'
    required: false
    default: '.'
  fail-on-error:
    description: 'Fail the action if mu diff encounters an error (default: false)'
    required: false
    default: 'false'
  update-comment:
    description: 'Update existing MU diff comment instead of creating new one (default: true)'
    required: false
    default: 'true'

outputs:
  diff-output:
    description: 'The full diff output in markdown format'
  has-changes:
    description: 'Whether semantic changes were detected (true/false)'
  comment-url:
    description: 'URL of the posted/updated comment'
  artifact-url:
    description: 'URL of the uploaded artifact (if artifact input is true)'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_BASE: ${{ inputs.base }}
    INPUT_HEAD: ${{ inputs.head }}
    INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
    INPUT_COMMENT: ${{ inputs.comment }}
    INPUT_ARTIFACT: ${{ inputs.artifact }}
    INPUT_ARTIFACT_NAME: ${{ inputs.artifact-name }}
    INPUT_MAX_COMMENT_SIZE: ${{ inputs.max-comment-size }}
    INPUT_WORKING_DIRECTORY: ${{ inputs.working-directory }}
    INPUT_FAIL_ON_ERROR: ${{ inputs.fail-on-error }}
    INPUT_UPDATE_COMMENT: ${{ inputs.update-comment }}
